### ISSUE TITLE
Runtime bug

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#304]
/cc @OlegYch 

The following snippets fail to complete (infinite spinner in the UI)

```scala
trait A {
  val a = "1"
  val b = a
}

new A {
  override val a = ("2")
  println(b)
}
```

Cause:

```
[ERROR] [07/30/2017 11:30:04.325] [Runner-akka.actor.default-dispatcher-2] [akka://Runner/user/SbtActor/SbtRunner] java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
   at java.util.concurrent.FutureTask.report(FutureTask.java:122)
   at java.util.concurrent.FutureTask.get(FutureTask.java:206)
   at com.olegych.scastie.sbt.SbtRunner.withTimeout(SbtRunner.scala:203)
   at com.olegych.scastie.sbt.SbtRunner.com$olegych$scastie$sbt$SbtRunner$$run(SbtRunner.scala:122)
   at com.olegych.scastie.sbt.SbtRunner$$anonfun$receive$1.applyOrElse(SbtRunner.scala:159)
   at akka.actor.Actor.aroundReceive(Actor.scala:513)
   at akka.actor.Actor.aroundReceive$(Actor.scala:511)
   at com.olegych.scastie.sbt.SbtRunner.aroundReceive(SbtRunner.scala:32)
   at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
   at akka.actor.ActorCell.invoke(ActorCell.scala:496)
   at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
   at akka.dispatch.Mailbox.run(Mailbox.scala:224)
   at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
   at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
   at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
   at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
   at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
   at com.olegych.scastie.sbt.SbtRunner.$anonfun$extractProblems$2(SbtRunner.scala:320)
   at scala.Option.map(Option.scala:146)
   at com.olegych.scastie.sbt.SbtRunner.extractProblems(SbtRunner.scala:320)
   at com.olegych.scastie.sbt.SbtRunner.$anonfun$processSbtOutput$1(SbtRunner.scala:229)
   at com.olegych.scastie.sbt.SbtRunner.$anonfun$processSbtOutput$1$adapted(SbtRunner.scala:223)
   at com.olegych.scastie.sbt.Sbt.collect(Sbt.scala:106)
   at com.olegych.scastie.sbt.Sbt.process(Sbt.scala:134)
   at com.olegych.scastie.sbt.Sbt.maybeReloadAndEval(Sbt.scala:232)
   at com.olegych.scastie.sbt.Sbt.eval(Sbt.scala:190)
   at com.olegych.scastie.sbt.SbtRunner.eval$1(SbtRunner.scala:73)
   at com.olegych.scastie.sbt.SbtRunner.$anonfun$run$3(SbtRunner.scala:117)
   at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
   at com.olegych.scastie.sbt.SbtRunner$$anon$1.call(SbtRunner.scala:199)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.lang.Thread.run(Thread.java:745)
```

https://github.com/scalacenter/scastie/blob/611b2a5ecf22d6dac7a1d80ce454cf45681fa26f/sbt-runner/src/main/scala/com.olegych.scastie.sbt/SbtRunner.scala#L320

Result in the REPL:

```scala
scala> trait A {
     |   val a = "1"
     |   val b = a
     | }
defined trait A

scala> 

scala> new A {
     |   override val a = ("2")
     |   println(b)
     | }
null
res0: A = $anon$1@14379273
```

**Comment by MasseGuillaume** [comment]
yep this is a nice bug lol. 

upickle.read[T]("null") => Option(null)

then

`Some(null).map`

Compilation info just happen to be the first thing we deserialize.

**Comment by MasseGuillaume** [comment]
Solved: https://scastie.scala-lang.org/MasseGuillaume/wqriFQtLSuqV9aIEMGeYSQ
