### ISSUE TITLE
Scala.js version is old

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scastie#355]
I was trying to use scalameta in Scastie and got the following error

![screen shot 2017-10-23 at 15 04 01](https://user-images.githubusercontent.com/1408093/31890454-7de5a91c-b803-11e7-87b0-26714d70c287.png)
```
org.scalajs.core.ir.IRVersionNotSupportedException: This version (0.6.17) of Scala.js IR is not supported. Supported versions are: 0.6.0, 0.6.13, 0.6.3, 0.6.4, 0.6.6, 0.6.14, 0.6.8, 0.6.5, 0.6.15

org.scalajs.core.ir.IRVersionNotSupportedException: Failed to deserialize info of file compiled with Scala.js 0.6.17 (supported: 0.6.0, 0.6.13, 0.6.3, 0.6.4, 0.6.6, 0.6.14, 0.6.8, 0.6.5, 0.6.15): /home/scastie/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-library_2.12/0.6.20/scalajs-library_2.12-0.6.20.jar:scala/Product5.sjsir
	at org.scalajs.core.tools.io.VirtualSerializedScalaJSIRFile$class.info(VirtualFiles.scala:148)
	at org.scalajs.core.tools.io.MemVirtualSerializedScalaJSIRFile.info(MemFiles.scala:104)
```

**Comment by OlegYch** [comment]
current version is 0.6.26, i suppose that should fix the issue
