### ISSUE TITLE
Embedded Scastie snippet shows wrong code

### ISSUE THREAD

**Issue by DaniRey** [scalacenter/scastie#359]
I created a trivial non-worksheet Scastie snippet
`object MyHelloWorld extends App {
  println("Hello world")
}`

and tried to embed it as follows.

`<html>
<head></head>
<body>
<h1>Hello World</h1>
<script src="https://scastie.scala-lang.org/y9KjATFzRu6WTV8BjpCETQ.js"></script>
</body>
</html>`

When opening this HTML file locally I see the following code in the embedded Scastie
`List("Hello", "World").mkString("", ", ", "!")`

but following the "to Scastie" link, brings me to the correct snippet.

**Comment by DaniRey** [comment]
The issue only occurs when opening the HTML file directly in a browser. When serving it from a local webserver it works as expected.

**Comment by MasseGuillaume** [comment]
Hehe, this is what I tried: https://codepen.io/MasseGuillaume/pen/KyNxzy and as you said it works fine.

It looks like something related to permissions.

**Comment by DaniRey** [comment]
Seems to be due to cross-origin request policy
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://scastie.scala-lang.org/api/snippets/y9KjATFzRu6WTV8BjpCETQ. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

**Comment by MasseGuillaume** [comment]
It look like it's not possible to fix: https://stackoverflow.com/a/8456586/449071

**Comment by DaniRey** [comment]
I will try to find a way to show a warning message to the user, in case this happens.

I will create a pull-request if I have an idea.

**Comment by MasseGuillaume** [comment]
Yup we could add a try catch in the RestClient
https://github.com/scalacenter/scastie/blob/master/client/src/main/scala/com.olegych.scastie.client/RestApiClient.scala

**Comment by DaniRey** [comment]
Unfortunately I can't get the build to run on Windows 10. 

`sbt server/reStart` fails during yarn execution because it thinks Python is not available :-(

Now I either need some yak shaving support to get this to run on my machine, or I unfortunately have to hand this back to you, without a pull request.

**Comment by MasseGuillaume** [comment]
Hey, thanks for trying it out. I'm sorry that it does not work on windows. Your contribution would be really valuable and I'm ready to assist you in installing a dev setup.

You need to install the following tools: `nodejs, yarn, sbt and a jdk`. I'm surprised you need to install python. If the error occurs in sbt, can you paste the stack you get via the `last` command.

Thanks !

**Comment by DaniRey** [comment]
Cool. I have all those tools installed.

I see two issues when trying to execute `startAll`

```
 delivered. [4] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[error] error C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\node-sass: Command failed.
[info] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[error] Exit code: 1
[error] Command: node scripts/build.js
[error] Arguments:
[error] Directory: C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\node-sass
[error] Output:
[error] Building: C:\Program Files\nodejs\node.exe C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
[error] gyp info it worked if it ends with ok
[error] gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
[error] gyp verb cli   'C:\\Users\\daniel.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-bundler\\main\\node_modules\\node-gyp\\bin\\node-gyp.js',
[error] gyp verb cli   'rebuild',
[error] gyp verb cli   '--verbose',
[error] gyp verb cli   '--libsass_ext=',
[error] gyp verb cli   '--libsass_cflags=',
[error] gyp verb cli   '--libsass_ldflags=',
[error] gyp verb cli   '--libsass_library=' ]
[error] gyp info using node-gyp@3.6.2
[error] gyp info using node@9.1.0 | win32 | x64
[error] gyp verb command rebuild []
[error] gyp verb command clean []
[error] gyp verb clean removing "build" directory
[error] gyp verb command configure []
[error] gyp verb check python checking for Python executable "python2" in the PATH
[error] gyp verb `which` failed Error: not found: python2
[error] gyp verb `which` failed     at getNotFoundError (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:13:12)
[error] gyp verb `which` failed     at F (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:68:19)
[error] gyp verb `which` failed     at E (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:80:29)
[error] gyp verb `which` failed     at C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:89:16
[error] gyp verb `which` failed     at C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\isexe\index.js:42:5
[error] gyp verb `which` failed     at C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\isexe\windows.js:36:5
[error] gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
[error] gyp verb `which` failed  python2 { Error: not found: python2
[error] gyp verb `which` failed     at getNotFoundError (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:13:12)
[error] gyp verb `which` failed     at F (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:68:19)
[error] gyp verb `which` failed     at E (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:80:29)
[error] gyp verb `which` failed     at C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:89:16
[error] gyp verb `which` failed     at C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\isexe\index.js:42:5
[error] gyp verb `which` failed     at C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\isexe\windows.js:36:5
[error] gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
[error] gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\daniel.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-bundler\\main\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\daniel.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-bundler\\main\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\daniel.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-bundler\\main\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\daniel.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-bundler\\main\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\daniel.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-bundler\\main\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\daniel.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-bundler\\main\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:166:21)',
[error] gyp verb `which` failed   code: 'ENOENT' }
[error] gyp verb check python checking for Python executable "python" in the PATH
[error] gyp verb `which` succeeded python C:\Python36\python.EXE
[error] gyp verb check python version `C:\Python36\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.3\r\n"
[error] gyp verb could not find "C:\Python36\python.EXE". checking python launcher
[error] gyp verb could not find "C:\Python36\python.EXE". guessing location
[error] gyp verb ensuring that file exists: C:\Python27\python.exe
[error] gyp ERR! configure error
[error] gyp ERR! stack Error: Can't find Python executable "C:\Python36\python.EXE", you can set the PYTHON env variable.
[error] gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\node-gyp\lib\configure.js:483:19)
[error] gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\node-gyp\lib\configure.js:508:16)
[error] gyp ERR! stack     at C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\graceful-fs\polyfills.js:284:29
[error] gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
[error] gyp ERR! System Windows_NT 10.0.15063
[error] gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\daniel.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-bundler\\main\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
[error] gyp ERR! cwd C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\node-sass
[error] gyp ERR! node -v v9.1.0
[error] gyp ERR! node-gyp -v v3.6.2
[error] gyp ERR! not ok
[error] Build failed with error code: 1
```

And

```
sbtRunner 17:16:29.967 WARN  a.r.t.n.NettyTransport:75 | Remote connection to [null] failed with java.net.ConnectException: Connection refused: no further information: /127.0.0.1:15000
sbtRunner 17:16:29.968 WARN  a.r.ReliableDeliverySupervisor:75 | Association with remote system [akka.tcp://Web@127.0.0.1:15000] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://Web@127.0.0.1:15000]] Caused by: [Connection refused: no further information: /127.0.0.1:15000]
sbtRunner DisassociatedEvent Disassociated [akka.tcp://SbtRunner@127.0.0.1:5150] -> [akka.tcp://Web@127.0.0.1:15000]
sbtRunner 17:16:29.968 INFO  a.r.RemoteActorRefProvider$RemoteDeadLetterActorRef:80 | Message [com.olegych.scastie.api.SbtRunnerConnect] from Actor[akka://SbtRunner/user/SbtActor#1078157347] to Actor[akka://SbtRunner/deadLetters] was not delivered. [4] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

The second one usually overshadows the first one, because it happens again and again. Yesterday I had a situation, where it didn't try to start `sbtRunner` and `ensimeRunner` when I execute `server:reStart` (today it does). 

For the second one, I guess the port is in a range which one is not allowed to listen on on Windows. But I haven't yet dug through the configurations to try to change it. 

Maybe I can find some time on th weekend to dig further into those issues. Hints are very welcome. Do you know if others have this build running on Windows?

**Comment by DaniRey** [comment]
Learned two things. 

1) Port 15000 is not an issue under windows. I'm currently not even sure if the akka "error" I see even is an issue or not.

2) The Python issue is a problem with yarn. I can reproduce it when I start yarn in the client/target... directory

```
D...@.... MINGW64 ~/git/scastie/client/target/scala-2.12/scalajs-bundler/main (master)
$ yarn
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/2] ⠂ waiting...
[2/2] ⠂ node-sass: gyp
[-/2] ⠂ waiting...
[-/2] ⠄ waiting...
error C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\node-gyp\bin\node-gyp.js r
ebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\daniel.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-bundler\\main\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.1.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:13:12
)
gyp verb `which` failed     at F (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:13:12
)
gyp verb `which` failed     at F (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\daniel.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-b
undler\\main\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\daniel.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-bundler\\main\\node_modul
es\\which\\which.js:68:19)\n    at E (C:\\Users\\daniel.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-bundler\\main\\node_modules\\which\\which.js:80:2
9)\n    at C:\\Users\\daniel.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-bundler\\main\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\daniel
.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-bundler\\main\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\daniel.rey\\git\\scastie\\client\\t
arget\\scala-2.12\\scalajs-bundler\\main\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python36\python.EXE
gyp verb check python version `C:\Python36\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.3\r\n"
gyp verb could not find "C:\Python36\python.EXE". checking python launcher
gyp verb could not find "C:\Python36\python.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\node-gyp\lib\configu
re.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\node-gyp\lib\configur
e.js:508:16)
gyp ERR! stack     at C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\daniel.rey\\git\\scastie\\client\\target\\scala-2.12\\scalajs-bundler\\main\\node_modules\\no
de-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\daniel.rey\git\scastie\client\target\scala-2.12\scalajs-bundler\main\node_modules\node-sass
gyp ERR! node -v v9.1.0
```

**Comment by MasseGuillaume** [comment]
Hum it look like you need python for https://github.com/sass/node-sass/issues/1176#issuecomment-323035618

**Comment by DaniRey** [comment]
Downgrading node to 8.9.1 (`nvm install 8.9.1 && nvm use 8.9.1`) fixed the build issue.

Now I'm free to work on the pull request.

**Comment by MasseGuillaume** [comment]
@DaniRey Amazing! Thanks for your perseverance.
