### ISSUE TITLE
RUN button not working

### ISSUE THREAD

**Issue by aravamk** [scalacenter/scastie#410]
I am not able run any scala code. the run button is greyed out please advise

**Comment by OlegYch** [comment]
@aravamk try creating new snippet with 'New' button

**Comment by Katrix** [comment]
Same here.

OS: Windows 10 64-bit
Browser: Firefox Nightly 63.0a1 (2018-08-27)
Also doesn't work in Chrome 68.0.3440.106

Here is an exception I found in my console on Firefox
```
org.scalajs.dom.ext.AjaxException app.js:20:60902
  at kd.prototype.Yq(https://scastie.scala-lang.org/public/app.js:20:445172) app.js:20:60902
  at kd.prototype.tc(https://scastie.scala-lang.org/public/app.js:20:445528) app.js:20:60902
  at _a/i.onreadystatechange</<(https://scastie.scala-lang.org/public/app.js:20:144362) app.js:20:60902
  at r(https://scastie.scala-lang.org/public/app.js:20:41703) app.js:20:60902
  at EventHandlerNonNull*k(https://scastie.scala-lang.org/public/app.js:20:39588) app.js:20:60902
  at _instrumentBreadcrumbs/</<(https://scastie.scala-lang.org/public/app.js:20:48931) app.js:20:60902
  at _a(https://scastie.scala-lang.org/public/app.js:20:144608) app.js:20:60902
  at Xt(https://scastie.scala-lang.org/public/app.js:20:78643) app.js:20:60902
  at kh(https://scastie.scala-lang.org/public/app.js:20:176063) app.js:20:60902
  at xn/n</</</<(https://scastie.scala-lang.org/public/app.js:20:92744) app.js:20:60902
  at N$.prototype.za(https://scastie.scala-lang.org/public/app.js:20:535849) app.js:20:60902
  at Je/</<(https://scastie.scala-lang.org/public/app.js:20:111933) app.js:20:60902
  at N$.prototype.za(https://scastie.scala-lang.org/public/app.js:20:535849) app.js:20:60902
  at qH.Sb/</<(https://scastie.scala-lang.org/public/app.js:20:382810) app.js:20:60902
  at N$.prototype.za(https://scastie.scala-lang.org/public/app.js:20:535849) app.js:20:60902
  at Hb/n</<(https://scastie.scala-lang.org/public/app.js:20:252947) app.js:20:60902
  at r(https://scastie.scala-lang.org/public/app.js:6:197617) app.js:20:60902
  at u(https://scastie.scala-lang.org/public/app.js:6:195965) app.js:20:60902
  at a(https://scastie.scala-lang.org/public/app.js:6:196182) app.js:20:60902
  at p(https://scastie.scala-lang.org/public/app.js:6:180304) app.js:20:60902
  at w(https://scastie.scala-lang.org/public/app.js:6:180432) app.js:20:60902
  at r(https://scastie.scala-lang.org/public/app.js:20:12710) app.js:20:60902
  at processEventQueue(https://scastie.scala-lang.org/public/app.js:6:181494) app.js:20:60902
  at r(https://scastie.scala-lang.org/public/app.js:20:987568) app.js:20:60902
  at handleTopLevel(https://scastie.scala-lang.org/public/app.js:20:987640) app.js:20:60902
  at i(https://scastie.scala-lang.org/public/app.js:20:1009748) app.js:20:60902
  at perform(https://scastie.scala-lang.org/public/app.js:6:187838) app.js:20:60902
  at batchedUpdates(https://scastie.scala-lang.org/public/app.js:20:1009297) app.js:20:60902
  at i(https://scastie.scala-lang.org/public/app.js:6:167937) app.js:20:60902
  at dispatchEvent(https://scastie.scala-lang.org/public/app.js:20:1010597) app.js:20:60902
  at r(https://scastie.scala-lang.org/public/app.js:20:41703) app.js:20:60902
  at EventListener.handleEvent*_instrumentTryCatch/</</<(https://scastie.scala-lang.org/public/app.js:20:47948) app.js:20:60902
  at listen(https://scastie.scala-lang.org/public/app.js:20:29620) app.js:20:60902
  at trapBubbledEvent(https://scastie.scala-lang.org/public/app.js:20:1010304) app.js:20:60902
  at listenTo(https://scastie.scala-lang.org/public/app.js:6:193397) app.js:20:60902
  at i(https://scastie.scala-lang.org/public/app.js:20:976387) app.js:20:60902
  at _updateDOMProperties(https://scastie.scala-lang.org/public/app.js:20:984237) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:20:980796) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:6:176631) app.js:20:60902
  at performInitialMount(https://scastie.scala-lang.org/public/app.js:20:999134) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:20:998017) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:6:176631) app.js:20:60902
  at mountChildren(https://scastie.scala-lang.org/public/app.js:20:993870) app.js:20:60902
  at _createInitialChildren(https://scastie.scala-lang.org/public/app.js:20:982629) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:20:980843) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:6:176631) app.js:20:60902
  at mountChildren(https://scastie.scala-lang.org/public/app.js:20:993870) app.js:20:60902
  at _createInitialChildren(https://scastie.scala-lang.org/public/app.js:20:982629) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:20:980843) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:6:176631) app.js:20:60902
  at mountChildren(https://scastie.scala-lang.org/public/app.js:20:993870) app.js:20:60902
  at _createInitialChildren(https://scastie.scala-lang.org/public/app.js:20:982629) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:20:980843) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:6:176631) app.js:20:60902
  at performInitialMount(https://scastie.scala-lang.org/public/app.js:20:999134) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:20:998017) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:6:176631) app.js:20:60902
  at mountChildren(https://scastie.scala-lang.org/public/app.js:20:993870) app.js:20:60902
  at _createInitialChildren(https://scastie.scala-lang.org/public/app.js:20:982629) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:20:980843) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:6:176631) app.js:20:60902
  at performInitialMount(https://scastie.scala-lang.org/public/app.js:20:999134) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:20:998017) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:6:176631) app.js:20:60902
  at performInitialMount(https://scastie.scala-lang.org/public/app.js:20:999134) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:20:998017) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:6:176631) app.js:20:60902
  at performInitialMount(https://scastie.scala-lang.org/public/app.js:20:999134) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:20:998017) app.js:20:60902
  at mountComponent(https://scastie.scala-lang.org/public/app.js:6:176631) app.js:20:60902
  at u(https://scastie.scala-lang.org/public/app.js:20:31982) app.js:20:60902
  at perform(https://scastie.scala-lang.org/public/app.js:6:187838) app.js:20:60902
  at a(https://scastie.scala-lang.org/public/app.js:20:32203) app.js:20:60902
  at perform(https://scastie.scala-lang.org/public/app.js:6:187838) app.js:20:60902
  at batchedUpdates(https://scastie.scala-lang.org/public/app.js:20:1009297) app.js:20:60902
  at i(https://scastie.scala-lang.org/public/app.js:6:167937) app.js:20:60902
  at _renderNewRootComponent(https://scastie.scala-lang.org/public/app.js:20:33447) app.js:20:60902
  at _renderSubtreeIntoContainer(https://scastie.scala-lang.org/public/app.js:20:34432) app.js:20:60902
  at render(https://scastie.scala-lang.org/public/app.js:20:34559) app.js:20:60902
  at Mn.prototype.main(https://scastie.scala-lang.org/public/app.js:20:363666) app.js:20:60902
  at {anonymous}()(https://scastie.scala-lang.org/public/app.js:20:36128) app.js:20:60902
  at n(https://scastie.scala-lang.org/public/app.js:1:143) app.js:20:60902
  at {anonymous}()(https://scastie.scala-lang.org/public/app.js:1:513) app.js:20:60902
  at {anonymous}()(https://scastie.scala-lang.org/public/app.js:1:49) app.js:20:60902
The connection to https://scastie.scala-lang.org/api/status-sse was interrupted while the page was loading. app.js:20:423871
Connection to status updates closed: None app.js:20:60902
XML Parsing Error: no root element found
Location: https://scastie.scala-lang.org/api/user/settings
Line Number 1, Column 1:
```

Also got an excpetion in my console on Chrome about the service being unavailable (503)

**Comment by MasseGuillaume** [comment]
@Katrix back online!

**Comment by Katrix** [comment]
Thanks for the quick reply
