### ISSUE TITLE
How to import org.apache.spark?

### ISSUE THREAD

**Issue by skulden** [scalacenter/scastie#448]
Hey guys, i cant import org.apache.spark

i go to building settings and insert in "extra sbt cfg":
`libraryDependencies += "org.apache.spark" % "spark-core 2.10" % "1.6.2"`

but i get

```
sbt.librarymanagement.ResolveException: Error downloading org.apache.spark:spark-core 2.10:1.6.2
  Not found
  Not found
  not found: /home/sbtRunnerContainer/.ivy2/local/org.apache.spark/spark-core 2.10/1.6.2/ivys/ivy.xml
  download error: Caught java.io.IOException: Server returned HTTP response code: 400 for URL: https://repo1.maven.org/maven2/org/apache/spark/spark-core 2.10/1.6.2/spark-core 2.10-1.6.2.pom (Server returned HTTP response code: 400 for URL: https://repo1.maven.org/maven2/org/apache/spark/spark-core 2.10/1.6.2/spark-core 2.10-1.6.2.pom) while downloading https://repo1.maven.org/maven2/org/apache/spark/spark-core 2.10/1.6.2/spark-core 2.10-1.6.2.pom
  download error: Caught java.io.IOException: Server returned HTTP response code: 400 for URL: http://scala-webapps.epfl.ch:8081/artifactory/scastie-ivy/org.apache.spark/spark-core 2.10/1.6.2/ivys/ivy.xml (Server returned HTTP response code: 400 for URL: http://scala-webapps.epfl.ch:8081/artifactory/scastie-ivy/org.apache.spark/spark-core 2.10/1.6.2/ivys/ivy.xml) while downloading http://scala-webapps.epfl.ch:8081/artifactory/scastie-ivy/org.apache.spark/spark-core 2.10/1.6.2/ivys/ivy.xml
  download error: Caught java.io.IOException: Server returned HTTP response code: 400 for URL: http://scala-webapps.epfl.ch:8081/artifactory/scastie-maven/org/apache/spark/spark-core 2.10/1.6.2/spark-core 2.10-1.6.2.pom (Server returned HTTP response code: 400 for URL: http://scala-webapps.epfl.ch:8081/artifactory/scastie-maven/org/apache/spark/spark-core 2.10/1.6.2/spark-core 2.10-1.6.2.pom) while downloading http://scala-webapps.epfl.ch:8081/artifactory/scastie-maven/org/apache/spark/spark-core 2.10/1.6.2/spark-core 2.10-1.6.2.pom

sbt.librarymanagement.ResolveException: Error downloading org.apache.spark:spark-core 2.10:1.6.2
  Not found
  Not found
  not found: /home/sbtRunnerContainer/.ivy2/local/org.apache.spark/spark-core 2.10/1.6.2/ivys/ivy.xml
  download error: Caught java.io.IOException: Server returned HTTP response code: 400 for URL: https://repo1.maven.org/maven2/org/apache/spark/spark-core 2.10/1.6.2/spark-core 2.10-1.6.2.pom (Server returned HTTP response code: 400 for URL: https://repo1.maven.org/maven2/org/apache/spark/spark-core 2.10/1.6.2/spark-core 2.10-1.6.2.pom) while downloading https://repo1.maven.org/maven2/org/apache/spark/spark-core 2.10/1.6.2/spark-core 2.10-1.6.2.pom
  download error: Caught java.io.IOException: Server returned HTTP response code: 400 for URL: http://scala-webapps.epfl.ch:8081/artifactory/scastie-ivy/org.apache.spark/spark-core 2.10/1.6.2/ivys/ivy.xml (Server returned HTTP response code: 400 for URL: http://scala-webapps.epfl.ch:8081/artifactory/scastie-ivy/org.apache.spark/spark-core 2.10/1.6.2/ivys/ivy.xml) while downloading http://scala-webapps.epfl.ch:8081/artifactory/scastie-ivy/org.apache.spark/spark-core 2.10/1.6.2/ivys/ivy.xml
  download error: Caught java.io.IOException: Server returned HTTP response code: 400 for URL: http://scala-webapps.epfl.ch:8081/artifactory/scastie-maven/org/apache/spark/spark-core 2.10/1.6.2/spark-core 2.10-1.6.2.pom (Server returned HTTP response code: 400 for URL: http://scala-webapps.epfl.ch:8081/artifactory/scastie-maven/org/apache/spark/spark-core 2.10/1.6.2/spark-core 2.10-1.6.2.pom) while downloading http://scala-webapps.epfl.ch:8081/artifactory/scastie-maven/org/apache/spark/spark-core 2.10/1.6.2/spark-core 2.10-1.6.2.pom
	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:245)
	at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:214)
	at scala.util.Either$LeftProjection.map(Either.scala:573)
	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:214)
	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2942)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
	at sbt.Execute.work(Execute.scala:289)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by OlegYch** [comment]
@skulden please see https://www.scala-sbt.org/1.x/docs/Cross-Build.html#Using+cross-built+libraries

**Comment by skulden** [comment]
> @skulden please see https://www.scala-sbt.org/1.x/docs/Cross-Build.html#Using+cross-built+libraries

now i can import the package but after the Scastie doesnt recognize the functions

i use
`import org.apache.spark.sql.functions._`

and after
```
var x = Array(1,2,3,4,4,5,6,7,7,8,8,9,10)
array_distinct(x)
```

and i get ` not found: value array_distinct`

**Comment by OlegYch** [comment]
@skulden sorry i'm not familiar with spark, you can find some people how are here https://gitter.im/spark-scala/Lobby
