### ISSUE TITLE
Standard input in Scastie?

### ISSUE THREAD

**Issue by amerpersonal** [scalacenter/scastie#460]
Hi, is there a possibility to enter standard input from keyboard in Scastie? My program goes like this
package sedmica1

```
object UlazIzlaz {

  def main(args: Array[String]): Unit = {

    println("Unesite godiste: ")
    val godiste = scala.io.StdIn.readInt()

    println("Unesite trenutnu godinu: ")
    val godina = scala.io.StdIn.readInt()

    val starost = godina - godiste
    println("Imate " + starost + "godina")
  }
}
```

But when it gets to first input, i.e val godiste = scala.io.StdIn.readInt()
everything blocks.

Is there anyway go read standardn input?

Sorry if this is not a good place for this question. In that case, please refer me to other place

Thanks

**Comment by OlegYch** [comment]
sorry this is currently not possible because scastie server resources are limited
though you can use scala.js target and execute the program in the browser like this https://scastie.scala-lang.org/EYGBu0mhRdSSzxTwEE2o0A

**Comment by bulent2k2** [comment]
This code runs only once and the second time I try to run it, it gives an error. E.g. https://scastie.scala-lang.org/bulent2k2/EhT7diVrQRaWCvmWX758mA/1

sbt.librarymanagement.ResolveException: Error downloading org.scala-js:scalajs-library_3:0.6.31
  Not found
  Not found
  not found: /home/sbtRunnerContainer/.ivy2/local/org.scala-js/scalajs-library_3/0.6.31/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scala-js/scalajs-library_3/0.6.31/scalajs-library_3-0.6.31.pom
  not found: http://scala-webapps.epfl.ch:8081/artifactory/scastie-ivy/org.scala-js/scalajs-library_3/0.6.31/ivys/ivy.xml
  not found: http://scala-webapps.epfl.ch:8081/artifactory/scastie-maven/org/scala-js/scalajs-library_3/0.6.31/scalajs-library_3-0.6.31.pom
Error downloading org.scastie:runtime-scala_sjs0.6_2.13:1.0.0-SNAPSHOT
  Not found
  Not found
  not found: /home/sbtRunnerContainer/.ivy2/local/org.scastie/runtime-scala_sjs0.6_2.13/1.0.0-SNAPSHOT/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scastie/runtime-scala_sjs0.6_2.13/1.0.0-SNAPSHOT/runtime-scala_sjs0.6_2.13-1.0.0-SNAPSHOT.pom
  not found: http://scala-webapps.epfl.ch:8081/artifactory/scastie-ivy/org.scastie/runtime-scala_sjs0.6_2.13/1.0.0-SNAPSHOT/ivys/ivy.xml
  not found: http://scala-webapps.epfl.ch:8081/artifactory/scastie-maven/org/scastie/runtime-scala_sjs0.6_2.13/1.0.0-SNAPSHOT/runtime-scala_sjs0.6_2.13-1.0.0-SNAPSHOT.pom
	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:345)
	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:314)
	at scala.util.Either$LeftProjection.map(Either.scala:573)
	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:314)
	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3690)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:831)
2
println(a)
Console (F3)
 [info] welcome to sbt 1.6.2 (Oracle Corporation Java 17-ea)
[info] loading settings for project scastie15027089890856847019-build from plugins.sbt ...
[info] loading settings for project scastie15027089890856847019 from build.sbt ...
