### ISSUE TITLE
Library lookup allows choosing a non-existent version of the dependency

### ISSUE THREAD

**Issue by danicheg** [scalacenter/scastie#471]
For example, type 'cats' in the dependency search bar, and then choose version 2.1.1. The result is: 
```scala 
sbt.librarymanagement.ResolveException: Error downloading org.typelevel:cats_2.12:2.1.1
  Not found
  Not found
  not found: /home/sbtRunnerContainer/.ivy2/local/org.typelevel/cats_2.12/2.1.1/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/typelevel/cats_2.12/2.1.1/cats_2.12-2.1.1.pom
  not found: http://scala-webapps.epfl.ch:8081/artifactory/scastie-ivy/org.typelevel/cats_2.12/2.1.1/ivys/ivy.xml
  not found: http://scala-webapps.epfl.ch:8081/artifactory/scastie-maven/org/typelevel/cats_2.12/2.1.1/cats_2.12-2.1.1.pom
  at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
  at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
  at scala.util.Either$LeftProjection.map(Either.scala:573)
  at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
  at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
  at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
  at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
  at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
  at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
  at scala.util.control.Exception$Catch.apply(Exception.scala:228)
  at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
  at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
  at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
  at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
  at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
  at scala.Function1.$anonfun$compose$1(Function1.scala:49)
  at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
  at sbt.std.Transform$$anon$4.work(Transform.scala:67)
  at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
  at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
  at sbt.Execute.work(Execute.scala:290)
  at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
  at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
  at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

**Comment by Sciss** [comment]
Also

> sbt.librarymanagement.ResolveException: Error downloading io.github.cquiroz:scalajavatime_sjs1_2.13:2.0.0

I think correct artefact is

https://search.maven.org/artifact/io.github.cquiroz/scala-java-time_sjs1_2.13/2.0.0/

**Comment by OlegYch** [comment]
@Sciss 
![image](https://user-images.githubusercontent.com/268312/97877862-798a4680-1d26-11eb-9a85-c9f294a9de3d.png)
the `scala-java-time` item works
i'm not sure what `scala-java-time / scalajavatime` is, please log the issue on scaladex side

**Comment by danwerner** [comment]
I ran into the same issue as the OP. Choosing simply "cats" as a library leads to the exact error in the original post, every time, no matter which versions of cats or Scala I selected.

I had to choose "cats / core" in order to make it work. According to the [version matrix](https://index.scala-lang.org/artifacts/typelevel/cats), the "cats / cats" artifact (which is resolved when you only specify "cats") has been deprecated since after version 0.9.0 and doesn't exist anymore for versions after this, is favor of "cats / core".

Is this a problem at Scaladex or Scastie that these non-existent artifacts are selectable?

**Comment by OlegYch** [comment]
@danwerner pretty sure it can only be fixed on scaladex side
https://index.scala-lang.org/api/search?q=cats&target=JVM&scalaVersion=2.13 shouldn't list artifacts not available for 2.13

**Comment by danwerner** [comment]
@OlegYch It's not that the artifact is not available for Scala 2.13. It is not available in the newer Cats versions, e.g. 2.3.0 or 2.2.0. It is only available in Cats versions 0.9.0 and below.

**Comment by OlegYch** [comment]
@danwerner that's a separate problem

**Comment by vincenzobaz** [comment]
Related to #329 ?

**Comment by danicheg** [comment]
@vincenzobaz yep seems the same.
