### ISSUE TITLE
Displaying null values causes unexpected exceptions in Worksheets

### ISSUE THREAD

**Issue by nrinaudo** [scalacenter/scastie#534]
# Steps to reproduce
Create a scastie that ends up evaluating a variable whose value is `null`, such as, for example:
```scala
va a = null

a
```

The Scala version doesn't appear to affect the issue.

See, for example: https://scastie.scala-lang.org/nrinaudo/9vU97MN7RvOWBYqzjNewww/40

# Expected behaviour

Something like the following is displayed:
```scala
val a = null

a // null: Null
```

# Observed behaviour

A rather large stack trace is displayed. It starts off with:
```
java.lang.NullPointerException
	at com.olegych.scastie.api.runtime.SharedRuntime.render(SharedRuntime.scala:17)
	at com.olegych.scastie.api.runtime.SharedRuntime.render$(SharedRuntime.scala:13)
	at com.olegych.scastie.api.runtime.Runtime$.render(Runtime.scala:11)
	at Playground$.delayedEndpoint$Playground$1(main.scala:5)
	at Playground$delayedInit$body.apply(main.scala:2)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[...]
```

**Comment by nrinaudo** [comment]
I'm happy to attempt a PR for this if this is deemed worth fixing.

**Comment by OlegYch** [comment]
@nrinaudo a pr would be great
