### ISSUE TITLE
`org.scalameta.invariants.InvariantFailedException` thrown when running a Scala 3 style match statement with Scala 2

### ISSUE THREAD

**Issue by KacperFKorban** [scalacenter/scastie#636]
### Reproduction

Scastie link: https://scastie.scala-lang.org/KacperFKorban/HSo7AYKzRYSo2OPi1R8YRw

Code:
```scala
() match
  case _: Unit => ()
```
Scala version: `2.13.8` (and probably any `2.x` version)

Result:

<details>

```scala
org.scalameta.invariants.InvariantFailedException: invariant failed:
when verifying cases.!=(null).&&(cases.nonEmpty)
found that cases.nonEmpty is false
where cases = List()
	at org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:19)
	at scala.meta.Term$Match$.internal$85(Trees.scala:125)
	at scala.meta.Term$Match$.apply(Trees.scala:125)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$matchClause$2(ScalametaParser.scala:1389)
	at scala.meta.internal.parsers.ScalametaParser.autoEndPos(ScalametaParser.scala:339)
	at scala.meta.internal.parsers.ScalametaParser.autoEndPos(ScalametaParser.scala:341)
	at scala.meta.internal.parsers.ScalametaParser.matchClause(ScalametaParser.scala:1389)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$expr$2(ScalametaParser.scala:1585)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:296)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:337)
	at scala.meta.internal.parsers.ScalametaParser.expr(ScalametaParser.scala:1449)
	at scala.meta.internal.parsers.ScalametaParser$$anonfun$templateStat$1.applyOrElse(ScalametaParser.scala:4185)
	at scala.meta.internal.parsers.ScalametaParser$$anonfun$templateStat$1.applyOrElse(ScalametaParser.scala:4171)
	at scala.PartialFunction.$anonfun$runWith$1(PartialFunction.scala:231)
	at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:230)
	at scala.meta.internal.parsers.ScalametaParser.statSeqBuf(ScalametaParser.scala:4123)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$templateStatSeq$1(ScalametaParser.scala:4163)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$templateStatSeq$1$adapted(ScalametaParser.scala:4162)
	at scala.meta.internal.parsers.ScalametaParser.scala$meta$internal$parsers$ScalametaParser$$listBy(ScalametaParser.scala:508)
	at scala.meta.internal.parsers.ScalametaParser.templateStatSeq(ScalametaParser.scala:4162)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$templateBody$1(ScalametaParser.scala:4008)
	at scala.meta.internal.parsers.ScalametaParser.inBracesOr(ScalametaParser.scala:231)
	at scala.meta.internal.parsers.ScalametaParser.inBraces(ScalametaParser.scala:227)
	at scala.meta.internal.parsers.ScalametaParser.templateBody(ScalametaParser.scala:4008)
	at scala.meta.internal.parsers.ScalametaParser.templateBodyOpt(ScalametaParser.scala:4016)
	at scala.meta.internal.parsers.ScalametaParser.template(ScalametaParser.scala:3930)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$template$1(ScalametaParser.scala:3952)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:296)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:337)
	at scala.meta.internal.parsers.ScalametaParser.template(ScalametaParser.scala:3939)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$templateOpt$1(ScalametaParser.scala:3982)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:296)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:337)
	at scala.meta.internal.parsers.ScalametaParser.templateOpt(ScalametaParser.scala:3971)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$objectDef$1(ScalametaParser.scala:3705)
	at scala.meta.internal.parsers.ScalametaParser.autoEndPos(ScalametaParser.scala:339)
	at scala.meta.internal.parsers.ScalametaParser.autoEndPos(ScalametaParser.scala:341)
	at scala.meta.internal.parsers.ScalametaParser.objectDef(ScalametaParser.scala:3697)
	at scala.meta.internal.parsers.ScalametaParser.tmplDef(ScalametaParser.scala:3574)
	at scala.meta.internal.parsers.ScalametaParser.topLevelTmplDef(ScalametaParser.scala:3555)
	at scala.meta.internal.parsers.ScalametaParser$$anonfun$4.applyOrElse(ScalametaParser.scala:4142)
	at scala.meta.internal.parsers.ScalametaParser$$anonfun$4.applyOrElse(ScalametaParser.scala:4130)
	at scala.PartialFunction.$anonfun$runWith$1(PartialFunction.scala:231)
	at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:230)
	at scala.meta.internal.parsers.ScalametaParser.statSeqBuf(ScalametaParser.scala:4123)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$14(ScalametaParser.scala:4337)
	at scala.Option.getOrElse(Option.scala:201)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$1(ScalametaParser.scala:4337)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:296)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:337)
	at scala.meta.internal.parsers.ScalametaParser.batchSource(ScalametaParser.scala:4292)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$source$1(ScalametaParser.scala:4285)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:296)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:337)
	at scala.meta.internal.parsers.ScalametaParser.source(ScalametaParser.scala:4285)
	at scala.meta.internal.parsers.ScalametaParser.entrypointSource(ScalametaParser.scala:4290)
	at scala.meta.internal.parsers.ScalametaParser.parseSourceImpl(ScalametaParser.scala:132)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$parseSource$1(ScalametaParser.scala:129)
	at scala.meta.internal.parsers.ScalametaParser.parseRuleAfterBOF(ScalametaParser.scala:56)
	at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:51)
	at scala.meta.internal.parsers.ScalametaParser.parseSource(ScalametaParser.scala:129)
	at scala.meta.parsers.Parse$.$anonfun$parseSource$1(Parse.scala:29)
	at scala.meta.parsers.Parse$$anon$1.apply(Parse.scala:36)
	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:25)
	at scala.meta.parsers.Api$XtensionParseInputLike.parse(Api.scala:14)
	at com.olegych.scastie.instrumentation.Instrument$.apply(Instrument.scala:199)
	at com.olegych.scastie.instrumentation.InstrumentedInputs$.apply(InstrumentedInputs.scala:23)
	at com.olegych.scastie.sbt.SbtProcess$$anonfun$4.applyOrElse(SbtProcess.scala:191)
	at com.olegych.scastie.sbt.SbtProcess$$anonfun$4.applyOrElse(SbtProcess.scala:177)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at akka.actor.FSM.processEvent(FSM.scala:851)
	at akka.actor.FSM.processEvent$(FSM.scala:848)
	at com.olegych.scastie.sbt.SbtProcess.processEvent(SbtProcess.scala:64)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:845)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:840)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at com.olegych.scastie.sbt.SbtProcess.aroundReceive(SbtProcess.scala:64)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

</details>

### Expectation

Compilation error probably.
scalac gives `'{' expected but 'case' found.`

**Comment by tgodzik** [comment]
Taking a look at it in https://github.com/scalameta/scalameta/pull/2830
