### ISSUE TITLE
Crash with `-source:future`

### ISSUE THREAD

**Issue by Sporarum** [scalacenter/scastie#778]
(In short: https://scastie.scala-lang.org/ZX2tmXGTRCWDQx0t9TbtPg )

When I add `"-source:future"` to my "Extra Sbt Configuration", and then click "Run", the page turns white, and the console (f12) writes:
```
RangeError: Invalid line number -1 in 1-line document
    line https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:1
    a https://scastie.scala-lang.org/public/app-7366d6ce.js:112
    apply__O__O https://scastie.scala-lang.org/public/app-7366d6ce.js:122
    Gc https://scastie.scala-lang.org/public/app-7366d6ce.js:128
    map__F1__O https://scastie.scala-lang.org/public/app-7366d6ce.js:171
    Ll_ https://scastie.scala-lang.org/public/app-7366d6ce.js:112
    o https://scastie.scala-lang.org/public/app-7366d6ce.js:112
    apply__O https://scastie.scala-lang.org/public/app-7366d6ce.js:122
    r https://scastie.scala-lang.org/public/app-7366d6ce.js:112
    apply__O https://scastie.scala-lang.org/public/app-7366d6ce.js:122
    run__Ljapgolly_scalajs_react_callback_Trampoline__O https://scastie.scala-lang.org/public/app-7366d6ce.js:51
    t https://scastie.scala-lang.org/public/app-7366d6ce.js:51
    apply__O https://scastie.scala-lang.org/public/app-7366d6ce.js:122
    run__Ljapgolly_scalajs_react_callback_Trampoline__O https://scastie.scala-lang.org/public/app-7366d6ce.js:51
    ow_ https://scastie.scala-lang.org/public/app-7366d6ce.js:170
    dispatch__O__V https://scastie.scala-lang.org/public/app-7366d6ce.js:171
    eB https://scastie.scala-lang.org/public/app-7366d6ce.js:167
    uq https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:100
    unstable_runWithPriority https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:85
    oi https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96
    Lr https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:100
    Ag https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:98
    YD https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96
    unstable_runWithPriority https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:85
    oi https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96
    YD https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96
    wn https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96
    gr https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:98
    enqueueSetState https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96
    setState https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:78
    modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__V https://scastie.scala-lang.org/public/app-7366d6ce.js:171
    modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__O https://scastie.scala-lang.org/public/app-7366d6ce.js:171
    modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__V https://scastie.scala-lang.org/public/app-7366d6ce.js:171
    modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__O https://scastie.scala-lang.org/public/app-7366d6ce.js:171
    s https://scastie.scala-lang.org/public/app-7366d6ce.js:171
    apply__O https://scastie.scala-lang.org/public/app-7366d6ce.js:122
    kv https://scastie.scala-lang.org/public/app-7366d6ce.js:127
    modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__O https://scastie.scala-lang.org/public/app-7366d6ce.js:171
    tt https://scastie.scala-lang.org/public/app-7366d6ce.js:112
    onMessage__Lcom_olegych_scastie_api_SnippetProgress__Z https://scastie.scala-lang.org/public/app-7366d6ce.js:88
    onMessage__O__Z https://scastie.scala-lang.org/public/app-7366d6ce.js:88
    onMessage__T__V https://scastie.scala-lang.org/public/app-7366d6ce.js:48
    Ao_ https://scastie.scala-lang.org/public/app-7366d6ce.js:86
    onmessage https://scastie.scala-lang.org/public/app-7366d6ce.js:88
[vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
    Wq https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:105
    Eg https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:98
    callback https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:98
    cN https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96
    tq https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:98
    oq https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:100
    unstable_runWithPriority https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:85
    oi https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96
    Gr https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:100
    Ag https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:98
    YD https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96
    unstable_runWithPriority https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:85
    oi https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96
    YD https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96
    wn https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96
    gr https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:98
    enqueueSetState https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96
    setState https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:78
    modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__V https://scastie.scala-lang.org/public/app-7366d6ce.js:171
    modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__O https://scastie.scala-lang.org/public/app-7366d6ce.js:171
    modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__V https://scastie.scala-lang.org/public/app-7366d6ce.js:171
    modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__O https://scastie.scala-lang.org/public/app-7366d6ce.js:171
    s https://scastie.scala-lang.org/public/app-7366d6ce.js:171
    apply__O https://scastie.scala-lang.org/public/app-7366d6ce.js:122
    kv https://scastie.scala-lang.org/public/app-7366d6ce.js:127
    modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__O https://scastie.scala-lang.org/public/app-7366d6ce.js:171
    tt https://scastie.scala-lang.org/public/app-7366d6ce.js:112
    onMessage__Lcom_olegych_scastie_api_SnippetProgress__Z https://scastie.scala-lang.org/public/app-7366d6ce.js:88
    onMessage__O__Z https://scastie.scala-lang.org/public/app-7366d6ce.js:88
    onMessage__T__V https://scastie.scala-lang.org/public/app-7366d6ce.js:48
    Ao_ https://scastie.scala-lang.org/public/app-7366d6ce.js:86
    onmessage https://scastie.scala-lang.org/public/app-7366d6ce.js:88
scala.scalajs.js.JavaScriptException: RangeError: Invalid line number -1 in 1-line document [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at line(https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:1:550) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at Ll_/a<(https://scastie.scala-lang.org/public/app-7366d6ce.js:112:79613) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at L.prototype.apply__O__O(https://scastie.scala-lang.org/public/app-7366d6ce.js:122:102804) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at Gc(https://scastie.scala-lang.org/public/app-7366d6ce.js:128:44451) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at Ko.prototype.map__F1__O(https://scastie.scala-lang.org/public/app-7366d6ce.js:171:131938) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at Ll_(https://scastie.scala-lang.org/public/app-7366d6ce.js:112:79518) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at jl_/o<(https://scastie.scala-lang.org/public/app-7366d6ce.js:112:81266) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at __.prototype.apply__O(https://scastie.scala-lang.org/public/app-7366d6ce.js:122:102416) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at jl_/r<(https://scastie.scala-lang.org/public/app-7366d6ce.js:112:81389) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at __.prototype.apply__O(https://scastie.scala-lang.org/public/app-7366d6ce.js:122:102416) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at yS.prototype.run__Ljapgolly_scalajs_react_callback_Trampoline__O(https://scastie.scala-lang.org/public/app-7366d6ce.js:51:128893) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at mr.prototype.when$extension__Ljapgolly_scalajs_react_callback_Trampoline__F0__Ljapgolly_scalajs_react_callback_Trampoline/t<(https://scastie.scala-lang.org/public/app-7366d6ce.js:51:123206) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at __.prototype.apply__O(https://scastie.scala-lang.org/public/app-7366d6ce.js:122:102416) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at yS.prototype.run__Ljapgolly_scalajs_react_callback_Trampoline__O(https://scastie.scala-lang.org/public/app-7366d6ce.js:51:128994) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at ow_(https://scastie.scala-lang.org/public/app-7366d6ce.js:170:45897) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at hy.prototype.dispatch__O__V(https://scastie.scala-lang.org/public/app-7366d6ce.js:171:25490) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at eB/<(https://scastie.scala-lang.org/public/app-7366d6ce.js:167:1735) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at uq(https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:100:6541) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at t.unstable_runWithPriority(https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:85:3806) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at oi(https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96:38475) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at Lr(https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:100:6013) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at Ag(https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:98:10716) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at YD/<(https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96:38697) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at t.unstable_runWithPriority(https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:85:3806) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at oi(https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96:38475) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at YD(https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96:38645) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at wn(https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96:38578) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at gr(https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:98:8417) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at enqueueSetState(https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:96:42559) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at ba.prototype.setState(https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js:78:1371) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at Er.prototype.modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__V(https://scastie.scala-lang.org/public/app-7366d6ce.js:171:98424) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at Er.prototype.modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__O(https://scastie.scala-lang.org/public/app-7366d6ce.js:171:99670) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at oc.prototype.modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__V(https://scastie.scala-lang.org/public/app-7366d6ce.js:171:105289) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at oc.prototype.modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__O(https://scastie.scala-lang.org/public/app-7366d6ce.js:171:107072) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at e$.prototype.modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__O/s<(https://scastie.scala-lang.org/public/app-7366d6ce.js:171:63999) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at __.prototype.apply__O(https://scastie.scala-lang.org/public/app-7366d6ce.js:122:102416) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at kv(https://scastie.scala-lang.org/public/app-7366d6ce.js:127:1273) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at e$.prototype.modState__F1__F0__Ljapgolly_scalajs_react_util_Effect$Dispatch__O(https://scastie.scala-lang.org/public/app-7366d6ce.js:171:64271) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at tt(https://scastie.scala-lang.org/public/app-7366d6ce.js:112:100200) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at uu.prototype.onMessage__Lcom_olegych_scastie_api_SnippetProgress__Z(https://scastie.scala-lang.org/public/app-7366d6ce.js:88:17295) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at uu.prototype.onMessage__O__Z(https://scastie.scala-lang.org/public/app-7366d6ce.js:88:21519) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at cf.prototype.onMessage__T__V(https://scastie.scala-lang.org/public/app-7366d6ce.js:48:5879) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at Ao_(https://scastie.scala-lang.org/public/app-7366d6ce.js:86:39272) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
  at Wd/this.Lcom_olegych_scastie_client_EventSourceStream__f_eventSource.onmessage(https://scastie.scala-lang.org/public/app-7366d6ce.js:88:743) [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
[object MessageEvent] [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
{"ts":1676986101770,"id":928,"snippetId":{"base64UUID":"ZX2tmXGTRCWDQx0t9TbtPg"},"compilationInfos":[{"severity":"Error","line":-1,"message":"`_` is no longer supported for a wildcard import; use `*` instead\nThis construct can be rewritten automatically under -rewrite -source future-migration."}],"instrumentations":[],"isDone":false,"isTimeout":false,"isSbtError":false,"isForcedProgramMode":false} [vendor-a5aa815d.js:105:169](https://scastie.scala-lang.org/public/assets/vendor-a5aa815d.js)
```

Adding more code does not seem to change the behaviour

**Comment by Sporarum** [comment]
Actually, this happens even with an empty page:
https://scastie.scala-lang.org/uZb8SBHdRr6xc92xpnvHzQ
vs
https://scastie.scala-lang.org/tvju2s9tQPqYsLwOq2urbA

**Comment by dhinojosa** [comment]
Ah, excellent. Someone posted the issue. I got the same.

**Comment by rochala** [comment]
I may have fixed it along the other issue. Gonna release new version tomorrow.
