### ISSUE TITLE
Scasctie suggests irrelevant library dependencies

### ISSUE THREAD

**Issue by VladKopanev** [scalacenter/scastie#849]
### Describe the bug

When I want to add a "cats" dependency in scastie settings. it suggest discontinued "cats" artefact, but with relevent "cats-core" version. This is unexpected behaviour.

### Scastie snippet link

https://scastie.scala-lang.org/VladKopanev/Bh1dsWCkTSavy0WGUBpkGg/6

### To Reproduce

1. Go to scastie
2. Click on Build Settings
3. Enter "cats" into libraries search input field
4. Click on "cats" search result
5. See the "cats" dependency being added with actual "cats-core" version
6. Try to compile with imports from the cats library
6. Get a compilation error "sbt.librarymanagement.ResolveException: Error downloading org.typelevel:cats_2.13:2.9.0 Not found"

### Expected behavior

I expect Scastie not to suggest "cats" with version "2.9" as a valid dependency and also downgrade the discontinued artefacts in the search result list

### Screenshot ( Optional )

<img width="1170" alt="Screenshot 2023-05-18 at 12 29 10" src="https://github.com/scalacenter/scastie/assets/7037262/a1dde923-de45-4e63-9e60-78e8f25ecb53">

### Version

Scastie website

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
sbt.librarymanagement.ResolveException: Error downloading org.typelevel:cats_2.13:2.9.0
  Not found
  Not found
  not found: /home/sbtRunnerContainer/.ivy2/local/org.typelevel/cats_2.13/2.9.0/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/typelevel/cats_2.13/2.9.0/cats_2.13-2.9.0.pom
  not found: http://scala-webapps.epfl.ch:8081/artifactory/scastie-ivy/org.typelevel/cats_2.13/2.9.0/ivys/ivy.xml
  not found: http://scala-webapps.epfl.ch:8081/artifactory/scastie-maven/org/typelevel/cats_2.13/2.9.0/cats_2.13-2.9.0.pom
	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
	at scala.util.Either$LeftProjection.map(Either.scala:573)
	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
```

**Comment by julienrf** [comment]
Thank you for the report. Scastie is using the Scaladex API under the hood, so the problem might originate in Scaladex instead.

Here is the request that is performed when searching for “cats”:

~~~ sh
curl 'https://index.scala-lang.org/api/search?target=JVM&scalaVersion=2.13&q=cats'
~~~

Then, when you select “cats” in the UI, it performs the following request to find the available versions:

~~~ sh
curl 'https://index.scala-lang.org/api/project?organization=typelevel&repository=cats&target=JVM&scalaVersion=3'
~~~

Which returns the following:

~~~ json
{
  "artifacts" : [ "cats-core", "algebra", "algebra-laws", "alleycats-core", "alleycats-laws", "cats-docs", "cats-free", "cats-jvm", "cats-kernel", "cats-kernel-laws", "cats-laws", "cats-testkit" ],
  "versions" : [ "2.9.0", "2.8.0", "2.7.0", "2.6.1" ],
  "groupId" : "org.typelevel",
  "artifactId" : "cats-core_3",
  "version" : "2.9.0"
}
~~~

**Comment by armanbilge** [comment]
Btw, in Scaladex the `cats` artifact is listed as deprecated on the settings page (visible to maintainers).

<img width="568" alt="Screen Shot 2023-05-19 at 0 12 18" src="https://github.com/scalacenter/scastie/assets/3119428/83c303f0-a42a-4c28-bb1b-5683d4ae680c">

**Comment by VladKopanev** [comment]
Hello @julienrf! as @armanbilge mentioned artefact is deprecated , so I would not expect to see it in scastie, or at least I expect to see a "deprecated" label on it. Otherwise it is super easy to be confused

**Comment by VladKopanev** [comment]
Thank you!

**Comment by adpi2** [comment]
https://github.com/scalacenter/scaladex/pull/1214 is deployed and I can confirm all the deprecated artifacts disappeared from the list of suggested deps in Scastie. We can potentially add them back with a different style (`cats (deprecated)` or ~~cats~~)

Also there is still a bug if two artifacts of the same project use a different versionning. That bug could be fixed by using the `/api/artifacts` endpoint instead of the `/api/projects`, as pointed by @julienrf in https://github.com/scalacenter/scastie/issues/849#issuecomment-1554113792.
